-- 删除所有表（按依赖顺序逆序删除）

DROP TABLE IF EXISTS site_settings CASCADE;
DROP TABLE IF EXISTS logins CASCADE;
DROP TABLE IF EXISTS resource_upload_tasks CASCADE;
DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS emoji_tasks CASCADE;
DROP TABLE IF EXISTS emoji_sprites CASCADE;
DROP TABLE IF EXISTS emojis CASCADE;
DROP TABLE IF EXISTS emoji_groups CASCADE;
DROP TABLE IF EXISTS footer_links CASCADE;
DROP TABLE IF EXISTS advertisements CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS links CASCADE;
DROP TABLE IF EXISTS feedbacks CASCADE;
DROP TABLE IF EXISTS ai_chat_messages CASCADE;
DROP TABLE IF EXISTS ai_chat_sessions CASCADE;
DROP TABLE IF EXISTS ai_models CASCADE;
DROP TABLE IF EXISTS comment_likes CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS article_views CASCADE;
DROP TABLE IF EXISTS article_likes CASCADE;
DROP TABLE IF EXISTS articles CASCADE;
DROP TABLE IF EXISTS article_tags CASCADE;
DROP TABLE IF EXISTS article_categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
