version: '1.0'
name: pr-pipeline
displayName: PRPipeline
triggers:
  trigger: manual
  pr:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: 1.12
        commands:
          - mkdir output
          - GOOS=linux GOARCH=amd64 go build -o output/main.amd64 main.go
          - GOOS=linux GOARCH=386 go build -o output/main.linux32 main.go
          - GOOS=windows GOARCH=amd64 go build -o output/main.win64.exe main.go
          - GOOS=windows GOARCH=386 go build -o output/main.win32.exe main.go
          - 'GOOS=darwin GOARCH=amd64 go build -o output/main.darwin main.go '
          - chmod +X output/main.linux32
          - ./output/main.linux32
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./output
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        dependsOn: build_golang
